[package]
name = "ref-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"

[dev-dependencies]
criterion = "*"

[profile.release]
opt-level = 3
lto = true

[[bench]]
name = "bench"
harness = false
